---
- name: Install packages required by rvm
  dnf:
    name: "{{item}}"
    state: present
  with_items:
    - autoconf
    - automake
    - gcc-c++
    - libffi-devel
    - libtool
    - readline-devel
    - libyaml-devel
      #- openssl-devel
