---
- hosts: mylaptop
  user: root
  vars:
    username: rory
    home_dir: '/home/{{username}}/'
    apps_dir: '{{home_dir}}.local/apps/'
  roles:
    - home
    - dotfiles
    - bash
    - docker
    - erlang
    - git
    - google-chrome
    - go
    - kernel
    - miscellaneous
    - mongo
    - mysql
    - node
    - openvpn
    - password-manager
    - php
    - postgresql
    - printer-scanners
    - redis
    - skype
    - sqlite
    - thunderbird
    - utils
    - neovim
    - xchat
    - vim
    - rvm-requirements
    - {
        role: rvm_io.ruby,
        rvm1_rubies: ['ruby-2.1.5', 'ruby-2.2.4', 'ruby-2.3.1', 'ruby-2.3.6', 'ruby-2.4.2', 'ruby-2.4.3'],
        rvm1_bundler_install: True,
        rvm1_install_path: '/home/rory/.rvm',
        rvm1_autolib_mode: 0,
        rvm1_user: 'root'
      }
