---
- name: Copy across mongo repo file
  copy:
    src: '../files/mongodb.repo'
    dest: '/etc/yum.repos.d/mongodb.repo'
    owner: root
    group: root
    mode: '0644'

- name: Install mongodb
  dnf:
    name: mongodb
    state: latest

- name: Install mongodb-server
  dnf:
    name: mongodb-server
    state: latest

- name: Start service
  service:
    name: mongod
    enabled: yes
    state: started

