---
- name: Arb utils
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - ack
    - apcupsd
    - dar
    - tomboy
    - gnote
    - ImageMagick
    - tlp
    - hamster-time-tracker
    - libxml2-devel
    - libxslt-devel
    - openldap-devel
    - qt5-qtwebkit-devel
    - memcached
    - inotify-tools
    - xorg-x11-server-Xvfb
    - pwgen

- name: Setup .bashrc for QT - so that gems like capybara compile correctly
  become: yes
  become_user: rory
  lineinfile:
    dest: '{{ home_dir }}/.bashrc'
    line: 'export QMAKE=/usr/bin/qmake-qt5'
