---
- name: Symlink gitconfig
  become: yes
  become_user: '{{ username }}'
  file:
    path: '{{home_dir}}.gitconfig'
    src: '{{home_dir}}.dotfiles/.gitconfig'
    state: link

- name: Symlink gitignore
  become: yes
  become_user: '{{ username }}'
  file:
    path: '{{home_dir}}.gitignore'
    src: '{{home_dir}}.dotfiles/.gitignore'
    state: link

- name: Setup .bashrc for git
  become: yes
  become_user: rory
  lineinfile:
    dest: '{{ home_dir }}/.bashrc'
    line: "{{ item }}"
  with_items:
    - 'export GIT_PS1_SHOWDIRTYSTATE=true'
    - 'export GIT_PS1_SHOWUNTRACKEDFILES=true'
    - 'export GIT_PS1_SHOWDIRTYSTATE=1'
    - 'source "/usr/share/git-core/contrib/completion/git-prompt.sh"'
    - 'PS1="\\W : \[\e[34;1m\]\$(__git_ps1)\[\e[0m\] : \[\e[32;1m\]\$(/home/rory/rvm/bin/rvm-prompt v g)\[\e[0m\]\$ "'
