---
- name: Install package
  dnf:
    name: golang
    state: present

- name: Setup .bashrc
  become: yes
  become_user: rory
  lineinfile:
    dest: '{{ home_dir }}/.bashrc'
    line: "{{ item }}"
  with_items:
    - 'PATH=$PATH:$HOME/data/git/go/bin'
    - 'export GOPATH=$HOME/data/git/go'
