---
- name: Unpack Node
  become: yes
  become_user: '{{ username }}'
  unarchive:
    src: ../files/node-v7.4.0-linux-x64.tar.xz
    dest: '{{ apps_dir }}'
    owner: '{{ username }}'
    group: '{{ username }}'

- name: Setup .bashrc for node
  become: yes
  become_user: '{{ username }}'
  lineinfile:
    dest: '{{ home_dir }}/.bashrc'
    line: '{{ item }}'
  with_items:
    - 'PATH=$HOME/.local/apps/node-v7.4.0-linux-x64/bin:$PATH # For nodejs'
    - 'export NODE_PATH=$HOME/.local/apps/node-v7.4.0-linux-x64/lib'

