---
- name: Install DNF config manager
  dnf:
    name: dnf-plugins-core
    state: latest

- name: Setup the Docker repo
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: Install docker ce
  dnf:
    name: docker-ce
    state: latest

- name: Install docker cli
  dnf:
    name: docker-cli
    state: latest

- name: Install containerd.io
  dnf:
    name: containerd.io
    state: latest

- name: Start docker service
  service:
    name: docker
    state: started
    enabled: yes
