---
- name: Install PHP packages
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - php
    - php-cli

- name: Create Composer directory
  file:
    owner: '{{ username }}'
    group: '{{ username }}'
    dest: '{{ apps_dir }}/composer'
    state: directory

- name: Create PHPUnit bin directory
  file:
    owner: '{{ username }}'
    group: '{{ username }}'
    dest: '{{ apps_dir }}/composer/bin'
    state: directory

- name: Copy across Composer executable
  copy:
    src: ../files/composer.phar
    dest: '{{ apps_dir }}/composer/bin/composer'

- name: Add PHPUnit path to .bashrc
  become: yes
  become_user: rory
  lineinfile:
    dest: '{{ home_dir }}/.bashrc'
    line: 'export PATH="$PATH:/home/rory/.local/apps/composer/bin"'
