---
- name: Install go
  hosts: mylaptop
  become: true
  tasks: 
    - name: Install package
      dnf:
        name: golang
        state: present

    - name: Setup .bashrc
      become_user: rory
      lineinfile:
        dest: ~/.bashrc
        line: "{{ item }}"
      with_items:
        - 'PATH=$PATH:$HOME/data/git/go/bin'
        - 'export GOPATH=$HOME/data/git/go'

