---
- name: Install and start mongodb
  hosts: mylaptop
  tasks:
    - name: Install mongodb
      dnf: name=mongodb state=latest

    - name: Install mongodb-server
      dnf: name=mongodb-server state=latest

    - name: Start service
      service: name=mongod enabled=yes state=started
