---
- name: Install Node
  hosts: mylaptop
  become: true
  tasks: 
    - name: Create apps directory
      file: dest=/home/rory/.local/apps state=directory owner=rory group=rory

    - name: Unpack Node
      unarchive: src=../files/node-v5.9.1-linux-x64.tar.xz dest=/home/rory/.local/apps
