---
- name: Install Node
  hosts: mylaptop
  become: true
  tasks: 
    - name: Create apps directory
      file: dest=/home/rory/.local/apps state=directory owner=rory group=rory

    - name: Unpack Node
      become_user: rory
      unarchive: src=../files/node-v6.5.0-linux-x64.tar.xz dest=~/.local/apps

    - name: Setup .bashrc for node
      become_user: rory
      lineinfile:
        dest: /home/rory/.bashrc
        line: "{{ item }}"
      with_items:
        - 'PATH=$HOME/.local/apps/node-v6.5.0-linux-x64/bin:$PATH # For nodejs'
        - 'export NODE_PATH=$HOME/.local/apps/node-v6.5.0-linux-x64/lib'

