---
- name: Arb utility stuff
  hosts: mylaptop
  become: true
  tasks:
    - name: Packages
      dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - ack
        - apcupsd
        - dar
        - tomboy
        - gnote
        - ImageMagick
        - tlp
        - hamster-time-tracker

    - name: Services
      service:
        name: fstrim.timer
        state: started
        enabled: yes
