---
- dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - neovim
    - python3-neovim

- file:
    dest: '{{ home_dir }}/.config/nvim' 
    state: directory
    owner: '{{ username }}'
    group: '{{ username }}'
    mode: 0755

- file:
    dest: '{{ home_dir }}/.config/nvim/autoload' 
    state: directory
    owner: '{{ username }}'
    group: '{{ username }}'
    mode: 0755

- copy:
    src: '../files/plug.vim'
    dest: '{{ home_dir }}/.config/nvim/autoload/plug.vim'
    owner: '{{ username }}'
    group: '{{ username }}'
    mode: 0644

- file:
    src: '{{ home_dir }}/.dotfiles/init.vim'
    dest: '{{ home_dir }}/.config/nvim/init.vim'
    state: link
    owner: '{{ username }}'
    group: '{{ username }}'
